all:
	echo "Type 'make clean' to delete all auxiliary files"

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.synctex.gz
	rm -f *.toc
	rm -f *.bbl
	rm -f *.blg
	rm -f *.lol
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
